@BASE_URL=http://localhost:3000

@accessToken=v7AUtnwfKfC3mLBI84y7S2tbvhBTzrfL.fwSmC+mP3NnioBIXVzg9Vidj9r08ZZI1lBKTmZ1/kVA=

### server health
GET {{BASE_URL}}/health


### auth - email sign up
POST {{BASE_URL}}/api/auth/sign-up/email
Content-Type: application/json

{
    "name": "Pocorib",
    "email": "pocorib849@ocuser.com",
    "password": "Pass@123"
}


### auth - email sign in
POST {{BASE_URL}}/api/auth/sign-in/email
Content-Type: application/json

{
    "email": "pocorib849@ocuser.com",
    "password": "Pass@123"
}


### auth - sign out
POST {{BASE_URL}}/api/auth/sign-out
Authorization: Bearer {{accessToken}}


### user - get me
GET {{BASE_URL}}/api/user
Authorization: Bearer {{accessToken}}

