@BASE_URL=http://localhost:3000

@accessToken=Pi8l1mhL8tyntqaDC0VsPTpioV3TBAsR.Q4cQkbtC3mMLeEHhlFYt8/KH7JzkBphvwoBz0nrXGng=

### server health
GET {{BASE_URL}}/health


### auth - email sign up
POST {{BASE_URL}}/api/auth/sign-up/email
Content-Type: application/json

{
    "name": "Sarixim",
    "email": "sarixim159@synsky.com",
    "password": "Pass@123"
}


### auth - email sign in
POST {{BASE_URL}}/api/auth/sign-in/email
Content-Type: application/json

{
    "email": "pocorib849@ocuser.com",
    "password": "Pass@123"
}


### auth - sign out
POST {{BASE_URL}}/api/auth/sign-out
Authorization: Bearer {{accessToken}}


### user - get me
GET {{BASE_URL}}/api/user
Authorization: Bearer {{accessToken}}


### room - create room
POST {{BASE_URL}}/api/room/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Test room",
    "adminId": "O7KJePDCcqwHWrl7C14qQza2CkvwO5Ag"
}


### room - join room
POST {{BASE_URL}}/api/room/join
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "inviteCode": "FBN4LC"
}


