name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev, main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm dlx prisma generate

      - name: Run Formatter Check
        run: pnpm format

      - name: Run Linter
        run: pnpm lint
